travis:
  secure:
    BINSTAR_TOKEN: Dx92PNXvyEmQDH0verl3WUjGne76o8JKEglcYoUfQsOzjNeun0O1VxB33gbnDzAHBidTR/c8LJZEyiGBSE1cXbg64gHI7cCfbhPNCl4LDi/ubcicFY3w3B99rQrpbI6X2vzWZf+rZNnbPBA4icgnT50a3F8EbqPpTiyysDESzr0kNSmnmoZRlsNp5f4QHOSH1Coq9/lyFC47XSS6DYvcOnUoRsVjiaEaAioIFkiCTQUK1jQEfvEmG+7XG/JTFYjHwzNrbSWTsGX1mH/E+qCa418D1Bc9KvgGb16kJYlqbS41IRz7wSwmepnixTsN7sazxOINl8lZDhv5Av37qzKSeXDAQdi/vw59pBC9IbZdyT+BBCit3KH2mE2gJyy4xy2X4Aa4nbp254pJ8eE0s/02OBQhkXuNQsTwimFe+jX08RSGa5s/kRecGQlQktvFxMdZk0B7skuNHkSxkJBTfwGhLJYDW+jFvAuqV2y8TtPolbqRbOPNYmaDhUWpSl2IR/7QW6RMINoed0Eicou2FjMDJkt0VDVdtF1yUsPGCXbH9gpZLSgeiUUx/N8DrxHeCJ6GVbqjCBizJqw9OqihKkqdevuEgwTq3fOFN/UqGqFT7Am+YScWM917jdKhH/09ZVSkeaj70E0s2y6mnbaaou5czhQ6EK2wGdnVdR6I6MujPvE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
