travis:
  secure:
    BINSTAR_TOKEN: q/F0wrZctFVWH0qWGgpOyf4ItK8SpsBPb2P9zz0GfSWro+3J5lipdKc0zFkzgabo9nbmWKnMWh03OsEux4Sr9K4ioVqhL78G+4jt+6Evh4K2DA4aE2Mh7uyKIAFI2Wy5ZSPqL1LbKNjqkvD6I6FcOAqNv5dbXtDgSCTRXGOymmBnNxxvyij4mtxkvhJYXM5n98PmD77bQeGSt1Cg4cejkajljZiu8pJDtG9DT9a0KPvw0Gd4+qQlgy1ahqd6CAWzrl/r1XJP9kDJQfgIMQSxfhc+3BC9ht1P1LRNmGs1z8IkDePpz7r8CKB4DFTz5o2gPk3AHvR9KgdDhoVVlopiafGd4n3Wcz2r+7Qu8+rv4MVh1HBw+r1Dt4f6/rvWmjCGAfPIfwQCXJhfIMhKwFHzUV2ZUP42kAcTmnMRC46A2UU2y1HYQNkVWb287A8H6iqVRgCL+91NaRCEDEHiLnoFqUH+RhSjcwfYBrZLTMnNKiXTMejcI/hDDvPmHH1sCztjYEGtWgrN9A2xfgYGGvkewlB3aeR0I9DxBQU+G9IAzaja5BpuWlPbnBEnJcaYlb3Sp7I7ijeuf8qt3fhSzS4xz9V8zI3miPbxpjgDqt7XoubK/HTHntMbE4k9UaPBpB1+n4ap12y1e5G5qeanXlEdscALmbQJ6taYGU9A+fm14CM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
